runmode: debug               # 开发模式, debug, release, test
addr: :9090                  # HTTP绑定端口
url: http://127.0.0.1:9090
max_check_count: 10
database:
  name: db
  addr: 127.0.0.1:3306
  username: root
  password: smartwell